name: Assign reviewers from OWNERS files
on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  assign_reviewers:
    steps:
      - name: Start hook plugin action
        uses: actions/cncf-infra/prow-github-action@main
