name: Assign reviewers from OWNERS files
on:
  # via gh workflow run
  workflow_dispatch:
  issues:
  issue_comment:
  # we don't run pull_requests... only pull_request_target
  # pull_request:
  pull_request_target:
  pull_request_review:
  pull_request_review_comment:
  push:
  status:
  discussion:
  discussion_comment:
  # pull_request:
  #   branches: ["main"]
permissions: write-all
# permissions:
#   actions: read|write|none
#   checks: read|write|none
#   contents: read|write|none
#   deployments: read|write|none
#   id-token: read|write|none
#   issues: read|write|none
#   discussions: read|write|none
#   packages: read|write|none
#   pages: read|write|none
#   pull-requests: read|write|none
#   repository-projects: read|write|none
#   security-events: read|write|none
#   statuses: read|write|none
jobs:
  prow_github_hook:
    name: Prow Github Hook
    runs-on: ubuntu-latest
    steps:
      - name: echo $GITHUB_EVENT_NAME
        run: echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME | tee event.name
      - name: cat event.json
        run: cat $GITHUB_EVENT_PATH | jq . | tee event.json
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            event.name
            event.json
      - uses: actions/checkout@v2
      - name: Start hook plugin action
        uses: cncf-infra/prow-github-action@main
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      #   with:
      #     hmac: ${{ secrets.HMAC }}
      #     hook-config: ${{ secrets.HOOK_CONFIG }}
      #     plugin-config: ${{ secrets.PLUGIN_CONFIG }}
