name: Assign reviewers from OWNERS files
on:
  # via gh workflow run
  workflow_dispatch:
  push:
  pull_request:
    branches: ["main"]
jobs:
  prow_github_hook:
    name: Prow Github Hook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Start hook plugin action
        uses: cncf-infra/prow-github-action@main
        with:
          plugin: ${{ secrets.PLUGIN }}
          hmac: ${{ secrets.HMAC }}
          gh-app-id: ${{ secrets.GH_APP_ID }}
          gh-app-pk: ${{ secrets.GH_APP_PK }}
          hook-config: ${{ secrets.HOOK_CONFIG }}
          plugin-config: ${{ secrets.PLUGIN_CONFIG }}
