name: Assign reviewers from OWNERS files
on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  prow_github_hook:
    name: Prow Github Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start hook plugin action
        uses: cncf-infra/prow-github-action@main
